spring:
  application:
    name: google-spreadsheet-issue-tracker

---
spring:
  config:
    activate:
      on-profile: google
  main:
    web-application-type: none
  shell:
    interactive:
      enabled: true


---
spring:
  config:
    activate:
      on-profile: memory
  main:
    web-application-type: none
  shell:
    interactive:
      enabled: true